fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # This one has been added to fail fast on syntax errors
      # before running expensive pylint
      - id: check-ast
        types_or:
          - python
          - pyi
      - id: check-json
      - id: check-yaml
        types: [file]
        files: \.(yaml|yml)$
  - repo: https://github.com/camptocamp/jsonschema-gentypes.git
    rev: "2.3.0"
    hooks:
      - id: jsonschema-gentypes
        stages: [manual]
        files: |
          (?x)^(
              \.jsonschema-gentypes\.yaml|
              oeb_level2/schemas/.*\.json
          )$
        args: ["--config", ".jsonschema-gentypes.yaml"]
  - repo: local
    hooks:
      - id: pylint
        name: Local PyLint
        language: system
        require_serial: true
        types:
          - python
        exclude: "^[^/]*env/|dev-[^/]*/"
        entry: pylint -j 0
      - id: mypy
        name: Local MyPy
        language: system
        types:
          - python
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
        entry: mypy --strict --show-error-codes --no-warn-unused-ignores
    
  - repo: https://github.com/inab/python-extended-json-schema-validator.git
    rev: v0.15.3
    hooks:
#      - id: identity
      - id: jsonschema_dir_validate
        name: Check jsonschema
        types:
          - json
        files: ^oeb_level2/schemas/.*\.(json|yaml)$
        require_serial: true
        pass_filenames: false
        args: [ oeb_level2/schemas ]
      - id: json_validation
        name: Validate prototype data
        types:
          - json
        files: ^(oeb_level2/schemas|minimal_dataset_examples|aggregation_examples)/.*\.(json|yaml)$
        require_serial: true
        pass_filenames: false
        args: [ "--guess-schema", "-c", "oeb_level2/schemas", "minimal_dataset_examples", "aggregation_examples" ]

#  - repo: https://github.com/ambv/black
#    rev: 22.6.0
#    hooks:
#      - id: black
#        exclude: "^[^/]*env/|dev-[^/]*/"
#        args: [--diff, --check]
